package commands

var ExpectedCollectionCommandCounts = map[string]int{
	"document":        31,
	"element":         21,
	"dictionary":      6,
	"media":           23,
	"doctype":         14,
	"datatype":        14,
	"template":        6,
	"forms":           6,
	"models-builder":  3,
	"member":          8,
	"member-group":    2,
	"logs":            7,
	"server":          5,
	"health":          4,
	"deploy":          3,
	"published-cache": 3,
	"redirect":        6,
	"indexer":         3,
	"mediatype":       8,
	"membertype":      8,
	"tree":            1,
	"auth":            5,
	"webhook":         7,
	"language":        7,
	"user":            14,
	"user-group":      7,
	"automate":        8,
}
