package commands

import (
	"context"
	"fmt"
	"sort"
	"strings"

	"github.com/spf13/cobra"

	"umbraco-cli/internal/api"
	"umbraco-cli/internal/schema"
	"umbraco-cli/internal/validate"
)

const memberPath = "/member"

func RegisterMember(root *cobra.Command, deps Dependencies) {
	member := &cobra.Command{
		Use:     "member",
		Aliases: []string{"members"},
		Short:   "Front-office member operations (login, profile, groups)",
		Long:    "Wraps /umbraco/management/api/v1/member and /filter/member. Lookups, edits, group assignment, plus convenience commands for the common diagnostic flows (approve, unlock, set-groups).",
	}
	member.AddCommand(memberList(deps))
	member.AddCommand(memberSearch(deps))
	member.AddCommand(memberGet(deps))
	member.AddCommand(memberCreate(deps))
	member.AddCommand(memberUpdate(deps))
	member.AddCommand(memberUpdateProperties(deps))
	member.AddCommand(memberDelete(deps))
	member.AddCommand(memberSetGroups(deps))
	root.AddCommand(member)
}

// memberFilterFields restricts the listing output to the agent-relevant
// fields by default. Full payload is one --fields away or via 'member get'.
const memberFilterDefaultFields = "id,username,email,isApproved,isLockedOut,isTwoFactorEnabled,failedPasswordAttempts,groups"

func memberList(deps Dependencies) *cobra.Command {
	var fields string
	var filter string
	var skip int
	var take int
	var triage readTriageOptions
	cmd := &cobra.Command{
		Use:   "list",
		Short: "List members (paginated; use --filter for substring search)",
		RunE: func(cmd *cobra.Command, args []string) error {
			params := map[string]any{}
			if strings.TrimSpace(filter) != "" {
				params["filter"] = filter
			}
			if cmd.Flags().Changed("skip") {
				params["skip"] = skip
			}
			if cmd.Flags().Changed("take") {
				params["take"] = take
			}
			result, err := deps.Client.Get(context.Background(), "/filter/member", api.RequestOptions{Fields: fields, Params: params})
			if err != nil {
				return err
			}
			return printResult(cmd, deps, applyReadTriage(applyFieldsProjection(result, fields), triage))
		},
	}
	cmd.Flags().StringVar(&fields, "fields", "", "Limit response fields (defaults to all; pass id,username,email,... for agent-friendly summaries)")
	cmd.Flags().StringVar(&filter, "filter", "", "Substring filter against member username/email")
	cmd.Flags().IntVar(&skip, "skip", 0, "Skip count")
	cmd.Flags().IntVar(&take, "take", 0, "Take count (0 = server default)")
	addReadTriageFlags(cmd, &triage)
	return cmd
}

func memberSearch(deps Dependencies) *cobra.Command {
	var fields string
	var take int
	var triage readTriageOptions
	cmd := &cobra.Command{
		Use:   "search <query>",
		Short: "Search members by username/email substring (shorthand for 'member list --filter')",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			params := map[string]any{"filter": args[0]}
			if cmd.Flags().Changed("take") {
				params["take"] = take
			}
			result, err := deps.Client.Get(context.Background(), "/filter/member", api.RequestOptions{Fields: fields, Params: params})
			if err != nil {
				return err
			}
			return printResult(cmd, deps, applyReadTriage(applyFieldsProjection(result, fields), triage))
		},
	}
	cmd.Flags().StringVar(&fields, "fields", memberFilterDefaultFields, "Limit response fields (default surfaces login-diagnosis fields; pass empty string for full payload)")
	cmd.Flags().IntVar(&take, "take", 0, "Maximum results")
	addReadTriageFlags(cmd, &triage)
	return cmd
}

func memberGet(deps Dependencies) *cobra.Command {
	var fields string
	cmd := &cobra.Command{
		Use:   "get <id>",
		Short: "Get a member by ID",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			result, err := deps.Client.Get(context.Background(), fmt.Sprintf("%s/%s", memberPath, args[0]), api.RequestOptions{Fields: fields})
			if err != nil {
				return err
			}
			return printResult(cmd, deps, applyFieldsProjection(result, fields))
		},
	}
	cmd.Flags().StringVar(&fields, "fields", "", "Limit response fields")
	return cmd
}

func memberCreate(deps Dependencies) *cobra.Command {
	var jsonPayload string
	var dryRun bool
	var printTemplate bool
	cmd := &cobra.Command{
		Use:   "create",
		Short: "Create a member",
		Long:  "POST /member. Use --print-template to see the accepted payload shape. The 'id' field is generated by the CLI if omitted.",
		RunE: func(cmd *cobra.Command, args []string) error {
			if printTemplate {
				return printResult(cmd, deps, schema.Templates["member.create"])
			}
			if err := requireValue("--json", jsonPayload); err != nil {
				return err
			}
			body, err := parsePayload(jsonPayload)
			if err != nil {
				return err
			}
			if _, err := ensurePayloadID(body); err != nil {
				return err
			}
			result, err := deps.Client.Post(context.Background(), memberPath, body, api.RequestOptions{DryRun: dryRun})
			if err != nil {
				return err
			}
			return printResult(cmd, deps, createResult(result, body, "icon"))
		},
	}
	cmd.Flags().StringVar(&jsonPayload, "json", "", "Create payload as JSON")
	cmd.Flags().BoolVar(&dryRun, "dry-run", false, "Validate request without executing")
	cmd.Flags().BoolVar(&printTemplate, "print-template", false, "Print an annotated JSON skeleton; substitute placeholders before passing to --json")
	return cmd
}

func memberUpdate(deps Dependencies) *cobra.Command {
	var jsonPayload string
	var mergeJSON string
	var dryRun bool
	cmd := &cobra.Command{
		Use:   "update <id>",
		Short: "Update a member (fetch-and-merge)",
		Long: `Both --json and --merge-json fetch the current member, deep-merge the patch, and PUT the merged result. This matches the datatype/document fix: an unmentioned field is never silently dropped.

Known API limitation (Umbraco 17.x): the Management API's UpdateMemberRequestModel does NOT accept the following fields, even though they appear on the read model. Including them in the patch returns 204 but the server-side value does not change:
  - isApproved
  - isLockedOut
  - failedPasswordAttempts

These are managed by the auth subsystem (login flow / backoffice action). The CLI does not silently rewrite the request — it sends what you ask — but agents should be aware that mutating these via 'member update' is a no-op.`,
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			hasJSON := strings.TrimSpace(jsonPayload) != ""
			hasMergeJSON := strings.TrimSpace(mergeJSON) != ""
			if hasJSON == hasMergeJSON {
				return fmt.Errorf("member update requires exactly one of --json or --merge-json")
			}
			raw := jsonPayload
			if hasMergeJSON {
				raw = mergeJSON
			}
			patch, err := parsePayload(raw)
			if err != nil {
				return err
			}
			current, err := fetchMemberObject(context.Background(), deps.Client, args[0])
			if err != nil {
				return err
			}
			merged := mergeAliasPayload(current, patch)
			result, err := deps.Client.Put(context.Background(), fmt.Sprintf("%s/%s", memberPath, args[0]), merged, api.RequestOptions{DryRun: dryRun, SkipValidation: true})
			if err != nil {
				return err
			}
			if !dryRun && result == nil {
				return printResult(cmd, deps, map[string]any{"updated": true})
			}
			return printResult(cmd, deps, result)
		},
	}
	cmd.Flags().StringVar(&jsonPayload, "json", "", "Update payload as JSON; merged into the current member so fields not mentioned are preserved")
	cmd.Flags().StringVar(&mergeJSON, "merge-json", "", "Alias for --json")
	cmd.Flags().BoolVar(&dryRun, "dry-run", false, "Validate request without executing")
	return cmd
}

func memberUpdateProperties(deps Dependencies) *cobra.Command {
	var jsonPayload string
	var dryRun bool
	cmd := &cobra.Command{
		Use:   "update-properties <id>",
		Short: "Update member custom property values (merges into values[] by alias)",
		Long:  "Accepts the same three input shapes as 'document update-properties': object {alias: value, ...}, array [{alias, value, culture?, segment?}, ...], or envelope {\"values\": [...]}. Merges into the member's existing values[] so untouched properties survive.",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			if err := requireValue("--json", jsonPayload); err != nil {
				return err
			}
			patch, err := buildUpdatePropertiesPatch(jsonPayload)
			if err != nil {
				return err
			}
			current, err := fetchMemberObject(context.Background(), deps.Client, args[0])
			if err != nil {
				return err
			}
			merged := mergeAliasPayload(current, patch)
			result, err := deps.Client.Put(context.Background(), fmt.Sprintf("%s/%s", memberPath, args[0]), merged, api.RequestOptions{DryRun: dryRun, SkipValidation: true})
			if err != nil {
				return err
			}
			if !dryRun && result == nil {
				return printResult(cmd, deps, map[string]any{"updated": true})
			}
			return printResult(cmd, deps, result)
		},
	}
	cmd.Flags().StringVar(&jsonPayload, "json", "", "Properties payload as JSON (object / array / envelope)")
	cmd.Flags().BoolVar(&dryRun, "dry-run", false, "Validate request without executing")
	return cmd
}

func memberDelete(deps Dependencies) *cobra.Command {
	var dryRun bool
	cmd := &cobra.Command{
		Use:   "delete <id>",
		Short: "Delete a member",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			result, err := deps.Client.Delete(context.Background(), fmt.Sprintf("%s/%s", memberPath, args[0]), api.RequestOptions{DryRun: dryRun})
			if err != nil {
				return err
			}
			if !dryRun && result == nil {
				return printResult(cmd, deps, map[string]any{"deleted": true})
			}
			return printResult(cmd, deps, result)
		},
	}
	cmd.Flags().BoolVar(&dryRun, "dry-run", false, "Validate request without executing")
	return cmd
}

// memberMutationSummary describes a member convenience mutation (approve /
// unlock / set-groups). Changed=false signals no PUT was issued because the
// member was already in the target state, matching the idempotent pattern
// used by 'datatype block add/remove'.
type memberMutationSummary struct {
	Action  string `json:"action"`
	ID      string `json:"id"`
	Changed bool   `json:"changed"`
	Message string `json:"message,omitempty"`
	Before  any    `json:"before,omitempty"`
	After   any    `json:"after,omitempty"`
}

func memberSetGroups(deps Dependencies) *cobra.Command {
	var setCSV string
	var addCSV string
	var removeCSV string
	var dryRun bool
	cmd := &cobra.Command{
		Use:   "set-groups <id>",
		Short: "Replace or modify a member's group memberships",
		Long: `Mutates the member's groups[] array. Pick one mode:

  --groups <guid,guid,…>       Replace the member's groups with this exact set
  --add-groups <guid,guid,…>   Append (idempotent — no PUT if all groups already present)
  --remove-groups <guid,guid,…> Remove (idempotent — no PUT if none of the groups are present)

Group GUIDs come from 'member-group list'. The PUT preserves every other field on the member.`,
		Args: cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			modes := 0
			for _, v := range []string{setCSV, addCSV, removeCSV} {
				if strings.TrimSpace(v) != "" {
					modes++
				}
			}
			if modes != 1 {
				return fmt.Errorf("member set-groups requires exactly one of --groups, --add-groups, or --remove-groups")
			}

			current, err := fetchMemberObject(context.Background(), deps.Client, args[0])
			if err != nil {
				return err
			}
			currentGroups := memberGroupGUIDs(current["groups"])
			var next []string
			switch {
			case strings.TrimSpace(setCSV) != "":
				next = uniqueCSV(setCSV)
			case strings.TrimSpace(addCSV) != "":
				next = mergeUniqueCSV(currentGroups, uniqueCSV(addCSV))
			case strings.TrimSpace(removeCSV) != "":
				next = subtractCSV(currentGroups, uniqueCSV(removeCSV))
			}
			for _, g := range next {
				if err := validate.String(g); err != nil {
					return err
				}
			}

			if stringSlicesEqualUnordered(currentGroups, next) {
				return printResult(cmd, deps, memberMutationSummary{
					Action: "set-groups", ID: args[0], Changed: false,
					Message: "groups already match the requested state",
					Before:  currentGroups, After: currentGroups,
				})
			}

			merged := mergeAliasPayload(current, map[string]any{"groups": stringsToAny(next)})
			result, err := deps.Client.Put(context.Background(), fmt.Sprintf("%s/%s", memberPath, args[0]), merged, api.RequestOptions{DryRun: dryRun, SkipValidation: true})
			if err != nil {
				return err
			}
			if dryRun {
				return printResult(cmd, deps, result)
			}
			return printResult(cmd, deps, memberMutationSummary{
				Action: "set-groups", ID: args[0], Changed: true,
				Before: currentGroups, After: next,
			})
		},
	}
	cmd.Flags().StringVar(&setCSV, "groups", "", "Comma-separated group GUIDs; replaces the member's groups[] with this exact set")
	cmd.Flags().StringVar(&addCSV, "add-groups", "", "Comma-separated group GUIDs to add (idempotent)")
	cmd.Flags().StringVar(&removeCSV, "remove-groups", "", "Comma-separated group GUIDs to remove (idempotent)")
	cmd.Flags().BoolVar(&dryRun, "dry-run", false, "Validate request without executing")
	return cmd
}

func fetchMemberObject(ctx context.Context, client *api.Client, id string) (map[string]any, error) {
	result, err := client.Get(ctx, fmt.Sprintf("%s/%s", memberPath, id), api.RequestOptions{})
	if err != nil {
		return nil, err
	}
	return decodeResult[map[string]any](result)
}

// memberGroupGUIDs extracts a string slice from the member's groups field,
// which can be either a flat array of GUID strings or an array of {id} refs
// depending on the API version. Both shapes are tolerated.
func memberGroupGUIDs(raw any) []string {
	items, ok := raw.([]any)
	if !ok {
		return nil
	}
	out := make([]string, 0, len(items))
	for _, item := range items {
		switch typed := item.(type) {
		case string:
			out = append(out, typed)
		case map[string]any:
			if id, ok := typed["id"].(string); ok && id != "" {
				out = append(out, id)
			}
		}
	}
	return out
}

func uniqueCSV(s string) []string {
	seen := map[string]struct{}{}
	out := []string{}
	for _, raw := range strings.Split(s, ",") {
		v := strings.TrimSpace(raw)
		if v == "" {
			continue
		}
		if _, exists := seen[v]; exists {
			continue
		}
		seen[v] = struct{}{}
		out = append(out, v)
	}
	return out
}

func mergeUniqueCSV(a []string, b []string) []string {
	seen := map[string]struct{}{}
	out := []string{}
	for _, v := range append(append([]string{}, a...), b...) {
		if _, exists := seen[v]; exists {
			continue
		}
		seen[v] = struct{}{}
		out = append(out, v)
	}
	return out
}

func subtractCSV(a []string, remove []string) []string {
	drop := map[string]struct{}{}
	for _, v := range remove {
		drop[v] = struct{}{}
	}
	out := []string{}
	for _, v := range a {
		if _, gone := drop[v]; gone {
			continue
		}
		out = append(out, v)
	}
	return out
}

func stringsToAny(in []string) []any {
	out := make([]any, len(in))
	for i, v := range in {
		out[i] = v
	}
	return out
}

func stringSlicesEqualUnordered(a, b []string) bool {
	if len(a) != len(b) {
		return false
	}
	ca := append([]string{}, a...)
	cb := append([]string{}, b...)
	sort.Strings(ca)
	sort.Strings(cb)
	for i := range ca {
		if ca[i] != cb[i] {
			return false
		}
	}
	return true
}
