# This file was generated by GoReleaser. DO NOT EDIT.
cask "albanist-umbraco-cli" do
  name "albanist-umbraco-cli"
  desc "Command-line client for the Umbraco Management API"
  homepage "https://github.com/albanistrefi/umbraco_CLI"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "umbraco"

  on_macos do
    on_intel do
      url "https://github.com/albanistrefi/umbraco_CLI/releases/download/v#{version}/umbraco-cli_#{version}_macOS_x86_64.tar.gz"
      sha256 "c67b37ffdee5ed82d11e5525becf50573a3eafe61fc3cccc42fd43f0ba6b81a2"
    end
    on_arm do
      url "https://github.com/albanistrefi/umbraco_CLI/releases/download/v#{version}/umbraco-cli_#{version}_macOS_arm64.tar.gz"
      sha256 "275e8123390662bbf54f9342fdd325dc498012df3d37cc7c052a7455a9c49f67"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/albanistrefi/umbraco_CLI/releases/download/v#{version}/umbraco-cli_#{version}_Linux_x86_64.tar.gz"
      sha256 "b517347ae5fc838fc08da2e51a99d223ccf2ce7cfe9f61bdf37d5973f9d1355a"
    end
    on_arm do
      url "https://github.com/albanistrefi/umbraco_CLI/releases/download/v#{version}/umbraco-cli_#{version}_Linux_arm64.tar.gz"
      sha256 "eee05765eebde9b7e76067723c794058c9bf8253d85ed9165decad65d748bb5a"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/umbraco"]
    end
  end

  caveats do
    "The `umbraco` binary expects these environment variables:"
    "  UMBRACO_BASE_URL"
    "  UMBRACO_CLIENT_ID"
    "  UMBRACO_CLIENT_SECRET"
    ""
    "The release archives are not notarized yet, so the cask clears the macOS"
    "quarantine attribute during installation."
  end

  # No zap stanza required
end
