package schema

// Templates holds annotated payload skeletons for --print-template flags.
// Unlike the operation schemas (generated from the OpenAPI document), these
// stay hand-curated: they encode workflow guidance — which fields the CLI
// generates, where IDs come from, version-specific caveats — that no spec
// carries.
var Templates = map[string]any{
	"document.create": map[string]any{
		"id":           "<uuid, optional; generated by CLI when omitted>",
		"documentType": map[string]any{"id": "<document type id, required>"},
		"template":     "<map {id} ref or null, required by newer servers>",
		"parent":       map[string]any{"id": "<parent document id, optional>"},
		"variants": []any{map[string]any{
			"name":    "<string, required>",
			"culture": "<culture, optional>",
		}},
		"values": []any{map[string]any{
			"alias":   "<property alias>",
			"value":   "<property value>",
			"culture": "<culture, optional>",
		}},
	},
	"doctype.create": map[string]any{
		"id":               "<uuid, optional; generated by CLI when omitted>",
		"name":             "<string, required>",
		"alias":            "<camelCase string, required>",
		"description":      "<string, optional>",
		"icon":             "<icon name, e.g. icon-document>",
		"allowedAsRoot":    "<boolean>",
		"variesByCulture":  "<boolean>",
		"variesBySegment":  "<boolean>",
		"isElement":        "<boolean, optional; true creates an element type (no own URL, intended for Block List/Grid)>",
		"allowedTemplates": "<array of {id} refs, optional; only valid for non-element types>",
		"defaultTemplate":  "<map {id} ref, optional; must be one of allowedTemplates>",
		"historyCleanup":   map[string]any{"preventCleanup": "<boolean>", "keepAllVersionsNewerThanDays": "<int|null>", "keepLatestVersionPerDayForDays": "<int|null>"},
		"collection":       "<map {id} ref to a list view data type, optional>",
		"properties": []any{map[string]any{
			"id":         "<uuid, optional>",
			"name":       "<string, required>",
			"alias":      "<camelCase string, required>",
			"dataType":   map[string]any{"id": "<guid from datatype search>"},
			"dataTypeId": "<guid, accepted shortcut; normalized to dataType.id>",
			"container":  map[string]any{"id": "<container id, optional>"},
			"sortOrder":  "<number>",
		}},
		"containers": []any{map[string]any{
			"id":        "<uuid>",
			"name":      "<tab or group name>",
			"parent":    map[string]any{"id": "<parent container id, optional>"},
			"type":      "<Tab|Group>",
			"sortOrder": "<number>",
		}},
		"compositions": "<array of {documentType: {id}, compositionType: 'Composition'|'Inheritance'} entries, optional>",
	},
	"doctype.update": map[string]any{
		"name":       "<string, required>",
		"alias":      "<camelCase string, required>",
		"properties": "<array; dataTypeId shortcut is accepted on property entries>",
	},
	"datatype.create": map[string]any{
		"id":          "<uuid, optional; generated by CLI when omitted>",
		"name":        "<string, required>",
		"alias":       "<camelCase string, optional>",
		"editorAlias": "<property editor alias, e.g. Umbraco.TextBox>",
		"configuration": map[string]any{
			"<settingAlias>": "<setting value>",
		},
	},
	"media.create": map[string]any{
		"id":        "<uuid, optional; generated by CLI when omitted>",
		"name":      "<string, required>",
		"mediaType": map[string]any{"id": "<media type id>"},
		"parent":    map[string]any{"id": "<parent media id, optional>"},
		"values": []any{map[string]any{
			"alias": "<property alias, e.g. umbracoFile>",
			"value": "<property value or temporary file reference>",
		}},
	},
	"template.create": map[string]any{
		"id":      "<uuid, optional; generated by CLI when omitted>",
		"name":    "<string, required>",
		"alias":   "<camelCase string, required>",
		"content": "<template markup, optional>",
	},
	"webhook.create": map[string]any{
		"id":              "<uuid, optional; generated by CLI when omitted>",
		"name":            "<string, optional display name>",
		"description":     "<string, optional>",
		"url":             "<target URL the webhook POSTs to, required>",
		"events":          []any{"<event alias from 'webhook events', e.g. Umbraco.ContentPublish>"},
		"enabled":         "<boolean, required>",
		"contentTypeKeys": []any{"<content type GUID; pass [] for all content types>"},
		"headers":         map[string]any{"<header-name>": "<header value; pass {} for none>"},
	},
	"user.create": map[string]any{
		"id":           "<uuid, optional; generated by CLI when omitted>",
		"email":        "<string, required, valid email>",
		"userName":     "<login name, required; usually the email>",
		"name":         "<display name, required>",
		"userGroupIds": []any{map[string]any{"id": "<user group GUID from 'user-group list'>"}},
		"kind":         "<Default for humans, Api for credential-only API users>",
	},
	"user-group.create": map[string]any{
		"id":                      "<uuid, optional; generated by CLI when omitted>",
		"name":                    "<display name, required>",
		"alias":                   "<camelCase string, required>",
		"icon":                    "<icon name, optional, e.g. icon-users>",
		"sections":                []any{"<section alias, e.g. Umb.Section.Content>"},
		"languages":               []any{"<language ISO code; pass [] with hasAccessToAllLanguages true>"},
		"hasAccessToAllLanguages": "<boolean, required>",
		"documentRootAccess":      "<boolean, required; true grants the whole content tree>",
		"documentStartNode":       "<map {id} ref, optional; used when documentRootAccess is false>",
		"mediaRootAccess":         "<boolean, required>",
		"mediaStartNode":          "<map {id} ref, optional>",
		"fallbackPermissions":     []any{"<single-letter permission verb codes matching the backoffice>"},
		"permissions":             []any{"<granular permission entries, optional; see an existing group via 'user-group get'>"},
	},
	"automate.catalogue.output-schema": map[string]any{
		"settings": map[string]any{
			"<settingAlias>": "<the settings the step would run with; shapes the dynamic output schema>",
		},
	},
	"automate.workspace.create": map[string]any{
		"alias":              "<camelCase string, required>",
		"name":               "<display name, required>",
		"serviceAccountKey":  "<backoffice user GUID the workspace's automations run as, required>",
		"userGroups":         []any{"<user group GUID allowed to edit automations here>"},
		"allowedConnections": []any{"<connection GUID automations here may use; pass [] for none>"},
	},
	"automate.connection.create": map[string]any{
		"alias":    "<camelCase string, required>",
		"name":     "<display name, required>",
		"type":     "<connection type alias from 'automate catalogue connection-types', required>",
		"settings": map[string]any{"<settingAlias>": "<credential value the connection type requires>"},
	},
	"automate.approvals.decide": map[string]any{
		"outcome": "<Approved or Rejected>",
		"comment": "<optional comment shown in the run history>",
	},
	"member.create": map[string]any{
		"id":         "<uuid, optional; generated by CLI when omitted>",
		"email":      "<string, required, valid email>",
		"username":   "<string, required; usually the email for front-office members>",
		"password":   "<string, required at create time>",
		"memberType": map[string]any{"id": "<member type id, required; from member-type endpoints>"},
		"variants": []any{map[string]any{
			"culture": "<culture, optional; null for invariant member types>",
			"segment": "<segment, optional; null for unsegmented>",
			"name":    "<string, required — the member's display name>",
		}},
		"groups": []any{"<member group GUID from 'member-group list'>"},
		"values": []any{map[string]any{
			"alias":   "<custom property alias defined on the member type>",
			"value":   "<property value>",
			"culture": "<culture, optional; null for invariant>",
			"segment": "<segment, optional; null for unsegmented>",
		}},
	},
}
