package skills

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/spf13/cobra"
	"github.com/spf13/pflag"
)

// blockedMethods lists destructive operations excluded from generated skills.
var blockedMethods = map[string]bool{
	"document.delete":   true,
	"doctype.delete":    true,
	"datatype.delete":   true,
	"template.delete":   true,
	"media.delete":      true,
	"dictionary.delete": true,
}

// Generate walks the cobra command tree and writes SKILL.md files to outputDir.
func Generate(root *cobra.Command, outputDir string, filter string, version string) error {
	if err := os.MkdirAll(outputDir, 0o755); err != nil {
		return fmt.Errorf("failed to create output directory: %w", err)
	}

	index := make([]indexEntry, 0)

	// Generate shared skill
	if filter == "" || strings.Contains("shared", filter) {
		if err := writeSkill(outputDir, "umbraco-shared", renderSharedSkill(version)); err != nil {
			return err
		}
		index = append(index, indexEntry{Name: "umbraco-shared", Description: "Shared reference: auth, global flags, safety rules, and config resolution", Category: "reference"})
	}

	// Generate per-collection skills from cobra subcommands
	for _, sub := range root.Commands() {
		name := sub.Name()

		// Skip non-API commands and hidden commands
		if isMetaCommand(name) || sub.Hidden {
			continue
		}

		if filter != "" && !strings.Contains(name, filter) {
			continue
		}

		skillName := fmt.Sprintf("umbraco-%s", name)
		md := renderCollectionSkill(name, sub, version)
		if err := writeSkill(outputDir, skillName, md); err != nil {
			return err
		}
		index = append(index, indexEntry{Name: skillName, Description: sub.Short, Category: "collection"})
	}

	// Generate recipe skills
	for _, recipe := range recipes {
		if filter != "" && !strings.Contains(recipe.Name, filter) {
			continue
		}

		skillName := fmt.Sprintf("recipe-%s", recipe.Name)
		md := renderRecipeSkill(recipe, version)
		if err := writeSkill(outputDir, skillName, md); err != nil {
			return err
		}
		index = append(index, indexEntry{Name: skillName, Description: recipe.Description, Category: "recipe"})
	}

	// Write index
	if filter == "" {
		if err := writeIndex(outputDir, index); err != nil {
			return err
		}
	}

	return nil
}

// metaCommands are non-API commands excluded from skill generation.
var metaCommands = map[string]bool{
	"schema":          true,
	"generate-skills": true,
	"help":            true,
	"completion":      true,
}

func isMetaCommand(name string) bool {
	return metaCommands[name]
}

func writeSkill(baseDir string, name string, content string) error {
	dir := filepath.Join(baseDir, name)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("failed to create skill directory %s: %w", dir, err)
	}
	path := filepath.Join(dir, "SKILL.md")
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return fmt.Errorf("failed to write %s: %w", path, err)
	}
	return nil
}

type indexEntry struct {
	Name        string
	Description string
	Category    string
}

func writeIndex(baseDir string, entries []indexEntry) error {
	var b strings.Builder
	b.WriteString("# CLI Skills Index\n\n")
	b.WriteString("> Auto-generated by `umbraco generate-skills`. Do not edit manually.\n\n")

	sections := []struct {
		category string
		heading  string
		subtitle string
	}{
		{"reference", "## Reference", "Shared patterns and conventions."},
		{"collection", "## Collections", "Per-resource CLI command skills."},
		{"recipe", "## Recipes", "Multi-step task sequences with real commands."},
	}

	for _, sec := range sections {
		items := make([]indexEntry, 0)
		for _, e := range entries {
			if e.Category == sec.category {
				items = append(items, e)
			}
		}
		if len(items) == 0 {
			continue
		}
		b.WriteString(fmt.Sprintf("%s\n\n%s\n\n", sec.heading, sec.subtitle))
		b.WriteString("| Skill | Description |\n|-------|-------------|\n")
		for _, item := range items {
			b.WriteString(fmt.Sprintf("| [%s](%s/SKILL.md) | %s |\n", item.Name, item.Name, item.Description))
		}
		b.WriteString("\n")
	}

	path := filepath.Join(baseDir, "INDEX.md")
	return os.WriteFile(path, []byte(b.String()), 0o644)
}

// renderSharedSkill produces the umbraco-shared SKILL.md content.
func renderSharedSkill(version string) string {
	var b strings.Builder

	b.WriteString(fmt.Sprintf(`---
name: umbraco-shared
description: "Umbraco CLI: Shared patterns for authentication, global flags, and safety rules."
metadata:
  version: %s
  requires:
    bins:
      - umbraco
---

# umbraco -- Shared Reference

## Installation

The `+"`umbraco`"+` binary must be on `+"`$PATH`"+`. Install via Homebrew or build from source.

`+"```bash"+`
brew install --cask albanist/tap/umbraco-cli
`+"```"+`

## Authentication

`+"```bash"+`
# Store credentials persistently
umbraco auth login --base-url "https://localhost:44314" --client-id "umbraco-back-office-api-user" --client-secret "your-secret"

# Verify credentials
umbraco auth status
`+"```"+`

Alternatively, set environment variables (highest precedence):

`+"```bash"+`
export UMBRACO_BASE_URL="https://localhost:44391"
export UMBRACO_CLIENT_ID="umbraco-back-office-api-user"
export UMBRACO_CLIENT_SECRET="your-secret"
`+"```"+`

## Config Precedence

1. Environment variables (`+"`UMBRACO_*`"+`)
2. Project `+"`"+`.umbracorc.json`+"`"+` or `+"`"+`.umbracorc`+"`"+`
3. Project `+"`"+`.umbraco-cli.env`+"`"+`
4. Project `+"`"+`.env`+"`"+`
5. User config `+"`"+`~/.umbraco/config.json`+"`"+`
6. Auto-discovered base URL from local .NET config
7. Fallback `+"`"+`https://localhost:44391`+"`"+`

## Global Flags

| Flag | Description |
|------|-------------|
| `+"`-o, --output <FORMAT>`"+` | Output format: `+"`json`"+`, `+"`table`"+`, `+"`plain`"+` |

## Safety Rules

- **Always** use `+"`--dry-run`"+` first for all mutating commands
- **Always** use `+"`--fields`"+` on reads to limit response size and protect context windows
- Prefer `+"`--json`"+` payloads over convenience flags for predictable execution
- Never construct IDs manually; reuse IDs from prior API responses
- Treat all input as untrusted

## Schema Introspection

Before calling any API method, inspect its expected parameters:

`+"```bash"+`
umbraco schema --list
umbraco schema document.update
umbraco schema datatype
`+"```"+`

Use `+"`umbraco schema`"+` output to build your `+"`--json`"+` and `+"`--params`"+` flags.
`, version))

	return b.String()
}

// renderCollectionSkill produces a SKILL.md for a top-level command group.
func renderCollectionSkill(name string, cmd *cobra.Command, version string) string {
	var b strings.Builder

	b.WriteString(fmt.Sprintf(`---
name: umbraco-%s
description: "%s"
metadata:
  version: %s
  requires:
    bins:
      - umbraco
    skills:
      - umbraco-shared
---

`, name, escapeYAML(cmd.Short), version))

	b.WriteString(fmt.Sprintf("# %s\n\n", name))
	b.WriteString("> **PREREQUISITE:** Read `../umbraco-shared/SKILL.md` for auth, global flags, and security rules.\n\n")
	b.WriteString(fmt.Sprintf("```bash\numbraco %s <command> [flags]\n```\n\n", name))

	// Collect subcommands, split into reads and mutations
	reads := make([]*cobra.Command, 0)
	mutations := make([]*cobra.Command, 0)

	subs := cmd.Commands()
	sort.Slice(subs, func(i, j int) bool {
		return subs[i].Name() < subs[j].Name()
	})

	for _, sub := range subs {
		if sub.Hidden {
			continue
		}
		endpointKey := fmt.Sprintf("%s.%s", name, sub.Name())
		if blockedMethods[endpointKey] {
			continue
		}
		if isMutationCommand(sub) {
			mutations = append(mutations, sub)
		} else {
			reads = append(reads, sub)
		}
	}

	// Read commands
	if len(reads) > 0 {
		b.WriteString("## Read Commands\n\n")
		b.WriteString("| Command | Description |\n|---------|-------------|\n")
		for _, sub := range reads {
			b.WriteString(fmt.Sprintf("| `%s %s` | %s |\n", name, sub.Use, sub.Short))
		}
		b.WriteString("\n")

		for _, sub := range reads {
			renderSubcommand(&b, name, sub)
		}
	}

	// Mutation commands
	if len(mutations) > 0 {
		b.WriteString("## Mutation Commands\n\n")
		b.WriteString("> **Safety:** Always use `--dry-run` first. Remove the flag only after verifying the dry-run output.\n\n")
		b.WriteString("| Command | Description |\n|---------|-------------|\n")
		for _, sub := range mutations {
			b.WriteString(fmt.Sprintf("| `%s %s` | %s |\n", name, sub.Use, sub.Short))
		}
		b.WriteString("\n")

		for _, sub := range mutations {
			renderSubcommand(&b, name, sub)
		}
	}

	// Discovering commands
	b.WriteString("## Discovering Commands\n\n")
	b.WriteString("```bash\n")
	b.WriteString(fmt.Sprintf("# Browse subcommands\numbraco %s --help\n\n", name))
	b.WriteString(fmt.Sprintf("# Inspect a specific endpoint schema\numbraco schema %s.<method>\n", name))
	b.WriteString("```\n")

	return b.String()
}

func renderSubcommand(b *strings.Builder, collection string, sub *cobra.Command) {
	b.WriteString(fmt.Sprintf("### %s\n\n", sub.Name()))

	b.WriteString(fmt.Sprintf("```bash\numbraco %s %s\n```\n\n", collection, sub.Use))

	// Long help text (caveats, API limitations, etc.) — agents reading the
	// generated SKILL.md should see the same warnings a human gets from
	// '<cmd> --help', otherwise they'll bypass guardrails the human author
	// expected the help text to convey.
	if long := strings.TrimSpace(sub.Long); long != "" && long != strings.TrimSpace(sub.Short) {
		b.WriteString(long)
		b.WriteString("\n\n")
	}

	// Flags table
	flags := collectFlags(sub)
	if len(flags) > 0 {
		b.WriteString("| Flag | Type | Default | Description |\n|------|------|---------|-------------|\n")
		for _, f := range flags {
			b.WriteString(fmt.Sprintf("| `%s` | %s | %s | %s |\n", f.Name, f.Type, f.Default, f.Description))
		}
		b.WriteString("\n")
	}

	// Safety note for mutations
	if isMutationCommand(sub) {
		b.WriteString("**Safe pattern:**\n\n")
		b.WriteString(fmt.Sprintf("```bash\n# 1. Dry run first\numbraco %s %s --dry-run\n\n", collection, sub.Use))
		b.WriteString(fmt.Sprintf("# 2. Execute\numbraco %s %s\n```\n\n", collection, sub.Use))
	}
}

type flagInfo struct {
	Name        string
	Type        string
	Default     string
	Description string
}

func collectFlags(cmd *cobra.Command) []flagInfo {
	flags := make([]flagInfo, 0)
	cmd.Flags().VisitAll(func(f *pflag.Flag) {
		if f.Hidden {
			return
		}
		def := f.DefValue
		if def == "" {
			def = "—"
		}
		flags = append(flags, flagInfo{
			Name:        fmt.Sprintf("--%s", f.Name),
			Type:        f.Value.Type(),
			Default:     def,
			Description: f.Usage,
		})
	})
	return flags
}

func isMutationCommand(cmd *cobra.Command) bool {
	hasDryRun := false
	cmd.Flags().VisitAll(func(f *pflag.Flag) {
		if f.Name == "dry-run" {
			hasDryRun = true
		}
	})
	return hasDryRun
}

func escapeYAML(s string) string {
	s = strings.ReplaceAll(s, `"`, `\"`)
	return s
}
